# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Farmacias' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Farmacias
pod 'Firebase/Analytics'
pod ‘Firebase/Auth’
pod ‘Firebase/Database’
pod ‘Firebase/Core’
pod 'Firebase/Firestore'

  target 'FarmaciasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FarmaciasUITests' do
    # Pods for testing
  end

end
